steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/vitalage/vitalage:$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/vitalage/vitalage:$COMMIT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "vitalage"
      - "--image"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/vitalage/vitalage:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"
      - "--port"
      - "8000"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/vitalage/vitalage:$COMMIT_SHA"
